# Generated by Django 2.0.4 on 2018-04-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('mav_id', models.TextField()),
                ('first_name', models.TextField(blank=True, default=None, null=True)),
                ('last_name', models.TextField(blank=True, default=None, null=True)),
                ('role', models.TextField(null=True)),
                ('sex', models.TextField(null=True)),
                ('birth_date', models.DateTimeField()),
                ('password', models.TextField()),
                ('email_id', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
